version: 0.2         
phases:
  build:
    commands:
      - npm i
      - npm i -g serverless
  post-build:
    commands:
      - serverless invoke local -f create-func
artifacts:
  files:
    - '**/*'
  name: myname-$(date +%Y-%m-%d) 