service: test-func 


provider:
  name: aws
  runtime: nodejs8.10

functions:
  create_func:
    handler: handler.create
    events:
      - http:
          path: users/create
          method: get
          cors: true
          integration: lambda
          authorizer: 
            name: authorizer
            arn: arn:aws:cognito-idp:us-east-1:325409168009:userpool/us-east-1_0LLDxBPzH
  list_func:
    handler: handler.list
    events:
      - http:
          path: users
          method: get
          cors: true

plugins: 
  - serverless-offline
  - serverless-dynamodb-local
